# 1

In [ ]:
import numpy as np

arr1 = np.random.rand(5,3) # 무작위의 데이터를 가진 5*3 행렬 생성 
arr2 = np.random.rand(3,2) # 무작위의 데이터를 가진 3*2 행렬 생성

dot = arr1 @ arr2 # 행렬곱 연산 -> 예시코드와는 다른 방법

print(dot, dot.shape)

[[0.94208081 0.65143858]
 [1.09891367 0.89631149]
 [0.71704211 0.42802563]
 [1.58075903 1.16742176]
 [0.97786683 0.6728686 ]] (5, 2)


* 2차원 공간에서는 행렬곱은 내적과 같은 역할

# 2

In [ ]:
arr1 = np.array([[5,7], [9,11]], float)
arr2 = np.array([[2,4],[6,8]], float)

# concatenate 연산
concat_1 = np.concatenate((arr1, arr2), axis = 0) # 행방향으로 더하기
concat_2 = np.concatenate((arr1, arr2), axis = 1) # 열방향으로 더하기

print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


* 행방향으로 더하기 -> 데이터가 밑으로 더해진다.
* 열방향으로 더하기 -> 데이터가 옆(오른쪽)으로 더해진다. 

# 3

In [ ]:
import numpy as np

xy = np.array([[1.,2.,3.,4.,5.,6.],[10.,20.,30.,40.,50.,60.]])

# 경사하강법을 위한 데이터 분리
x_train = xy[0] # xy의 첫번째 행 데이터 가져오기
y_train = xy[1] # xy의 두번째 행 데이터 가져오기

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


# 4

In [ ]:
# array형태로 출력하기 위해 파라미터에 1 추가
beta_gd = np.random.rand(1) # weight : 직선의 기울기(임의의 값)
bias = np.random.rand(1) # bias : y 절편(임의의 값)

print(beta_gd, bias)

[0.49217731] [0.98429294]


# 5

In [5]:
import numpy as np

xy = np.array([[1.,2.,3.,4.,5.,6.],
               [3.,6.,9.,12.,15.,18.]])

# 경사하강법을 위한 데이터 분리
x_train = xy[0] # xy의 첫번째 행 데이터 가져오기
y_train = xy[1] # xy의 두번째 행 데이터 가져오기

# array형태로 출력하기 위해 파라미터에 1 추가
beta_gd = np.random.rand(1) # weight : 직선의 기울기(임의의 값)
bias = np.random.rand(1) # bias : y 절편(임의의 값)


learning_rate = 0.01

for i in range(1000):
    error = np.sum((y_train - (x_train * beta_gd + bias))**2) / len(y_train) # 차이의 제곱을 이용해서 계산 -> 루트 필요없음(sqrt x)
    grad_beta_gd = - (2 / len(y_train)) * np.sum((y_train - x_train*beta_gd - bias) @ x_train.T)
    grad_bias = - (2 / len(y_train)) * np.sum(y_train - (x_train * beta_gd + bias))

    beta_gd = beta_gd - 0.01 * grad_beta_gd
    bias = bias - 0.01 * grad_bias


    if i % 100 == 0:
        print('Epoch ({:10d}/1000) error: {:10f}, beta_gd : {:10f}, bias:{:10f}'.format(i, error, beta_gd.item(), bias.item()))

Epoch (         0/1000) error: 102.589722, beta_gd :   1.176845, bias:  0.230698
Epoch (       100/1000) error:   0.036163, beta_gd :   2.899110, bias:  0.431930
Epoch (       200/1000) error:   0.017406, beta_gd :   2.930005, bias:  0.299661
Epoch (       300/1000) error:   0.008378, beta_gd :   2.951440, bias:  0.207897
Epoch (       400/1000) error:   0.004032, beta_gd :   2.966310, bias:  0.144233
Epoch (       500/1000) error:   0.001941, beta_gd :   2.976627, bias:  0.100065
Epoch (       600/1000) error:   0.000934, beta_gd :   2.983784, bias:  0.069422
Epoch (       700/1000) error:   0.000450, beta_gd :   2.988750, bias:  0.048163
Epoch (       800/1000) error:   0.000216, beta_gd :   2.992195, bias:  0.033414
Epoch (       900/1000) error:   0.000104, beta_gd :   2.994585, bias:  0.023182
