In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape, arr.ndim)

(3, 3) 2


In [2]:
import torch


torch_tensor_1 = torch.FloatTensor([1,2,3])
torch_tensor_2 = torch.FloatTensor([[4],[5],[6]])

print(torch_tensor_1 + torch_tensor_2)

tensor([[5., 6., 7.],
        [6., 7., 8.],
        [7., 8., 9.]])


In [4]:
import torch

torch_tensor = torch.FloatTensor([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])

print(torch_tensor.squeeze(), torch_tensor.squeeze().shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.Size([3, 3])


In [5]:
torch_tensor = torch.FloatTensor([[1,2,3,4],[5,6,7,8]])
torch_tensor = torch_tensor.view([-1,2])

print(torch_tensor)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [6]:
torch_tensor_1 = torch.FloatTensor([[1,2,3,4]])
torch_tensor_2 = torch.FloatTensor([[5,6,7,8]])

print(torch.cat([torch_tensor_1, torch_tensor_2], axis = 0))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


In [13]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

hypothesis = x_train * W + b

In [9]:
x_train

tensor([[1.],
        [2.],
        [3.]])

In [10]:
y_train

tensor([[2.],
        [4.],
        [6.]])

In [11]:
W

tensor([0.], requires_grad=True)

In [12]:
b

tensor([0.], requires_grad=True)

In [14]:
hypothesis

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [22]:
x_train = torch.FloatTensor([[73,80,75,77],
                            [93,88,93,95],
                            [89,91,90,89],
                            [96,98,100,97],
                            [73,66,70,68]])

W = torch.zeros(torch.Size([4,1]), requires_grad = True)

print(W.shape)

torch.Size([4, 1])
